export const theme = {
    light: {
        transparent: '--transparent',
        title: '--title',
        titleInput: '--titleInput',
        background: '--background',
        background2: '--background2',
        bckModal: '--bckModal',
        addProfile: '--addProfile',
        body: '--body',
        container: '--container',
        white2: '--white2',
        white1: '--white1',
        white: '--white',
        background3: '--background3',
        line: '--line',
        inputBg: '--inputBg',
        purple: '--purple',
        red: '--red',
    },
    dark: {
        transparent: '--transparent',
        background2: '--white',
        title: '--titleDark',
        titleInput: '--titleInputDark',
        background: '--background',
        bckModal: '--bckModal',
        addProfile: '--white1',
        body: '--titleDark',
        container: '--white',
        white2: '--white2',
        white1: '--white1',
        white: '--background2',
        background3: '--background3',
        line: '--line',
        inputBg: '--inputBg',
        purple: '--purple',
        red: '--red',
    }
}
